#Site
title: So Cereal
description: Coolest SW guild
logo: favicon.png
url: socereal.club
rss_url: /feed.xml

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Comment
comment:
  disqus: kongsong
  # duoshuo: kongsong
  # youyan: 2122392
  laibili: MTAyMC8yODgzNC81NDA0

# Website analytics
google_analytics: UA-82494501-1
baidu_analytics: 5b31ffbbdc6cff18727f3adf75a03777    #from //hm.baidu.com/hm.js?***

# Author information:
author:
  #resume: /resume
  name: So Cereal #the name of Blog section
  about_me:

# Social Links
# email:         email@email.com
# google.plus:   username
# twitter:       username
# facebook:      username
github:        socereal
# stackoverflow: id/username
# linkedin:      username
# xing:          username
# instagram:     username
# lastfm:        username
# tumblr:        username
# pinterest:     username
# foursquare:    username
# steam:         username
# dribbble:      username
# youtube:       username
# soundcloud:    username
# weibo:         username
# flickr:        username
# codepen:       username
# keybase:       username
# xmpp:          username@server.com
# hackernews:    username
# behance:       username
discord: https://discord.gg/eJ4dyKE

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile,.sass-cache,.DS_Store,.idea]
